# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-05 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmention', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentWebMention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField()),
                ('source', models.URLField()),
                ('target', models.URLField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
