# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-05 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmention', '0002_sentwebmention'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentwebmention',
            name='status_code',
            field=models.CharField(default=200, max_length=3),
            preserve_default=False,
        ),
    ]
