# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-12 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmention', '0003_sentwebmention_status_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='webmentionresponse',
            name='status_key',
            field=models.CharField(default='', max_length=6),
            preserve_default=False,
        ),
    ]
