# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-14 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmention', '0005_auto_20190512_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='webmentionresponse',
            name='status_code',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
    ]
