# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-22 05:12
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('webmention', '0007_delete_sentwebmention'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webmentionresponse',
            name='id',
        ),
        migrations.AddField(
            model_name='webmentionresponse',
            name='status',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
