# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-22 05:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webmention', '0008_auto_20190522_0512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webmentionresponse',
            name='status_key',
        ),
    ]
