# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-01 22:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webmention', '0010_auto_20190522_0517'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='webmentionresponse',
            unique_together=set([('response_to', 'source')]),
        ),
    ]
